### ISSUE TITLE
Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.

### ISSUE THREAD

**Issue by SametSahin10** [transitive-bullshit/puppeteer-lottie-cli#11]
Getting this error when executing installation command which is
`sudo npm install -g puppeteer-lottie-cli`
Although the documentation does not say it explicitly, I added sudo at the beggining to give the necessary permission. Below is the full version of the error. I'm working on MacOS Catalina 10.15.1
```
/usr/local/bin/puppeteer-lottie -> /usr/local/lib/node_modules/puppeteer-lottie-cli/index.js

> puppeteer@1.20.0 install /usr/local/lib/node_modules/puppeteer-lottie-cli/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/puppeteer-lottie-cli/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/puppeteer-lottie-cli/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/puppeteer-lottie-cli/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/puppeteer-lottie-cli/node_modules/puppeteer/.local-chromium'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sametsahin/.npm/_logs/2020-02-16T18_13_20_661Z-debug.log
```

**Comment by SametSahin10** [comment]
Not getting error with the command in [this](https://github.com/puppeteer/puppeteer/issues/2173#issuecomment-399745457) answer.
`sudo npm install -g puppeteer --unsafe-perm=true --allow-root`
I've replaced `puppeteer` with `puppeteer-lottie-cli`

**Comment by yousifnimah** [comment]
Working, thanks
