### ISSUE TITLE
Command results in Invalid regular expression

### ISSUE THREAD

**Issue by bobbyint** [transitive-bullshit/puppeteer-lottie-cli#18]
Running `puppeteer-lottie -i Animation.json -o 'frame-%d.png' ` in the terminal inside the folder that contains Animation.json results in SyntaxError: `Invalid regular expression: /^.*?\((?<label>.*?)[,)]/: Invalid group`

Logs: 

```
SyntaxError: Invalid regular expression: /^.*?\((?<label>.*?)[,)]/: Invalid group
    at Object.<anonymous> (/usr/local/lib/node_modules/puppeteer-lottie-cli/node_modules/ow/dist/source/index.js:1:26679)
    at r (/usr/local/lib/node_modules/puppeteer-lottie-cli/node_modules/ow/dist/source/index.js:1:186)
    at Object.module.exports.r (/usr/local/lib/node_modules/puppeteer-lottie-cli/node_modules/ow/dist/source/index.js:1:11962)
    at r (/usr/local/lib/node_modules/puppeteer-lottie-cli/node_modules/ow/dist/source/index.js:1:186)
    at module.exports.Object.defineProperty.value (/usr/local/lib/node_modules/puppeteer-lottie-cli/node_modules/ow/dist/source/index.js:1:985)
    at Object.<anonymous> (/usr/local/lib/node_modules/puppeteer-lottie-cli/node_modules/ow/dist/source/index.js:1:994)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
```

**Comment by gdimoff** [comment]
same here

**Comment by lmaix** [comment]
same for me

**Comment by SoftCreatR** [comment]
Same here
